services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "DockerIsTheBest!"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
